# Generated by Django 3.2.7 on 2021-10-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0002_auto_20211007_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_in_stock',
            field=models.IntegerField(blank=True, default=0, help_text='Amount in stock'),
        ),
    ]
