# Generated by Django 3.2.7 on 2021-10-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0003_product_amount_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
