# Generated by Django 3.2.7 on 2021-11-01 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0010_auto_20211030_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerName', models.CharField(max_length=50)),
                ('discountPercentage', models.PositiveIntegerField()),
                ('expiry', models.DateField()),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newadmin.category')),
            ],
        ),
    ]
