# Generated by Django 3.2.7 on 2021-11-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0011_categoryoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, upload_to='banner_images')),
                ('banner_name', models.CharField(max_length=50)),
                ('expiry', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
