# Generated by Django 3.2.7 on 2021-11-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartcopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='guest_token',
            field=models.UUIDField(blank=True, default=0, null=True),
        ),
    ]
