# Generated by Django 3.2.7 on 2021-11-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_guest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='guest_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
