# Generated by Django 3.2.7 on 2021-10-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
