# Generated by Django 3.2.7 on 2021-10-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order placed', 'order placed'), ('item shipped', 'item shipped'), ('order deliverd', 'order deliverd'), ('order cancelled', 'order cancelled')], default='order placed', max_length=50),
        ),
    ]
