# Generated by Django 3.2.7 on 2021-10-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('order_placed', 'order placed'), ('item_shipped', 'item shipped'), ('order_deliverd', 'order deliverd'), ('order_cancelled', 'order cancelled')], default='order placed', max_length=50, null=True),
        ),
    ]
