# Generated by Django 3.2.7 on 2021-10-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0008_auto_20211010_1720'),
        ('order', '0011_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newadmin.product'),
        ),
    ]
