# Generated by Django 3.2.7 on 2021-10-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_stock',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
