# Generated by Django 3.2.7 on 2021-10-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
