# Generated by Django 3.2.7 on 2021-10-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20211027_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.ordernumber'),
        ),
    ]
